# -*- coding: utf-8 -*-
"""Crawler Manual (Crawl4AI) v3.1 - Working (helper Gemini exp 1206).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cB_NTB3t1wIS3EyXdek0SflBjt14pzqo

# v1

## passo 1
"""

!pip install -U crawl4ai

!crawl4ai-setup

!crawl4ai-doctor

!python -m playwright install --with-deps chromium

"""## Passo 2: Adaptar o código"""

# OBS.: As duas linhas baixo não são necessárias no Colab
# parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# sys.path.append(parent_dir)

"""Passo 3: Implantar a solução"""

from google.colab import drive
drive.mount('/content/drive/')

"""## Passo 4: Monitorar e obter resultados"""

# Instalar dependências
!pip install -U crawl4ai
!crawl4ai-setup
!crawl4ai-doctor
!python -m playwright install --with-deps chromium

# Importar bibliotecas
import asyncio
from typing import List
from crawl4ai import AsyncWebCrawler, BrowserConfig, CrawlerRunConfig
from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator

# Função para rastreamento sequencial
async def crawl_sequential(urls: List[str]):
    print("\n=== Sequential Crawling with Session Reuse ===")

    browser_config = BrowserConfig(
        headless=True,
        # For better performance in Docker or low-memory environments:
        extra_args=["--disable-gpu", "--disable-dev-shm-usage", "--no-sandbox"],
    )

    crawl_config = CrawlerRunConfig(
        markdown_generator=DefaultMarkdownGenerator()
    )

    # Criar o crawler (abre o navegador)
    crawler = AsyncWebCrawler(config=browser_config)
    await crawler.start()

    try:
        session_id = "session1"  # Reutilizar a mesma sessão em todas as URLs
        for url in urls:
            result = await crawler.arun(
                url=url,
                config=crawl_config,
                session_id=session_id
            )
            if result.success:
                print(f"Successfully crawled: {url}")
                # Exemplo: verificar o tamanho do markdown
                print(f"Markdown length: {len(result.markdown_v2.raw_markdown)}")
            else:
                print(f"Failed: {url} - Error: {result.error_message}")
    finally:
        # Depois que todas as URLs forem concluídas, fechar o crawler (e o navegador)
        await crawler.close()

# Função principal
async def main():
    urls = [
        "https://ai.pydantic.dev/agents/",
        "https://ai.pydantic.dev/models/",
        "https://ai.pydantic.dev/dependencies/",
        "https://ai.pydantic.dev/tools/"
    ]
    await crawl_sequential(urls)

# Executar a função principal
#asyncio.run(main()) # <-- LINHA que possívelmente deu erro
await main()

!ls

!ls /content/drive/MyDrive/'Projetos Python - Google Colab (Colab Notebooks)'/Crawl4AI/Pydantic

!zip -r /content/arquivos.zip /content/drive/MyDrive/pasta_com_seus_arquivos

"""My Drive/Projetos Python - Google Colab (Colab Notebooks)/Crawl4AI/Pydantic"""



"""# v2 - Modificação para baixar .md no diretório "/content/drive/MyDrive/Projetos Python - Google Colab (Colab Notebooks)/Crawl4AI/Pydantic"
"""

!pip install -U crawl4ai

# Instalar dependências
!pip install -U crawl4ai
!crawl4ai-setup
!crawl4ai-doctor
!python -m playwright install --with-deps chromium

# Montar o Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Importar bibliotecas
import asyncio
from typing import List
from crawl4ai import AsyncWebCrawler, BrowserConfig, CrawlerRunConfig
from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator

# Definir o diretório de saída
output_directory = "/content/drive/MyDrive/Projetos Python - Google Colab (Colab Notebooks)/Crawl4AI/Pydantic"

# Função para rastreamento sequencial
async def crawl_sequential(urls: List[str]):
    print("\n=== Sequential Crawling with Session Reuse ===")

    browser_config = BrowserConfig(
        headless=True,
        # For better performance in Docker or low-memory environments:
        extra_args=["--disable-gpu", "--disable-dev-shm-usage", "--no-sandbox"],
    )

    crawl_config = CrawlerRunConfig(
        markdown_generator=DefaultMarkdownGenerator(),
        output_dir=output_directory  # Configurar o diretório de saída aqui
    )

    # Criar o crawler (abre o navegador)
    crawler = AsyncWebCrawler(config=browser_config)
    await crawler.start()

    try:
        session_id = "session1"  # Reutilizar a mesma sessão em todas as URLs
        for url in urls:
            result = await crawler.arun(
                url=url,
                config=crawl_config,
                session_id=session_id
            )
            if result.success:
                print(f"Successfully crawled: {url}")
                # Exemplo: verificar o tamanho do markdown
                print(f"Markdown length: {len(result.markdown_v2.raw_markdown)}")
            else:
                print(f"Failed: {url} - Error: {result.error_message}")
    finally:
        # Depois que todas as URLs forem concluídas, fechar o crawler (e o navegador)
        await crawler.close()

# Função principal
async def main():
    urls = [
        "https://ai.pydantic.dev/agents/",
        "https://ai.pydantic.dev/models/",
        "https://ai.pydantic.dev/dependencies/",
        "https://ai.pydantic.dev/tools/"
    ]
    await crawl_sequential(urls)

# Executar a função principal (usando await no Colab)
await main()

# Instalar dependências
!pip install -U crawl4ai
!crawl4ai-setup
!crawl4ai-doctor
!python -m playwright install --with-deps chromium

# Montar o Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Importar bibliotecas
import asyncio
from typing import List
from crawl4ai import AsyncWebCrawler, BrowserConfig, CrawlerRunConfig
from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator

# Definir o diretório de saída
output_directory = "/content/drive/MyDrive/Projetos Python - Google Colab (Colab Notebooks)/Crawl4AI/Pydantic"

# Função para rastreamento sequencial (modificada)
async def crawl_sequential(urls: List[str]):
    print("\n=== Sequential Crawling with Session Reuse ===")

    browser_config = BrowserConfig(
        headless=True,
        extra_args=["--disable-gpu", "--disable-dev-shm-usage", "--no-sandbox"],
    )

    crawl_config = CrawlerRunConfig(
        markdown_generator=DefaultMarkdownGenerator()
        # Remova output_dir daqui
    )

    # Criar o crawler (abre o navegador)
    crawler = AsyncWebCrawler(config=browser_config)
    await crawler.start()

    try:
        session_id = "session1"  # Reutilizar a mesma sessão em todas as URLs
        for url in urls:
            result = await crawler.arun(
                url=url,
                config=crawl_config,
                session_id=session_id
            )
            if result.success:
                print(f"Successfully crawled: {url}")
                print(f"Markdown length: {len(result.markdown_v2.raw_markdown)}")

                # Salvar o arquivo manualmente
                filename = os.path.join(output_directory, f"{url.replace('/', '_')}.md") # Nome do arquivo baseado na URL
                os.makedirs(os.path.dirname(filename), exist_ok=True) # Cria o diretório se necessário
                with open(filename, "w") as f:
                    f.write(result.markdown_v2.raw_markdown)
                print(f"Markdown saved to: {filename}")
            else:
                print(f"Failed: {url} - Error: {result.error_message}")
    finally:
        # Depois que todas as URLs forem concluídas, fechar o crawler (e o navegador)
        await crawler.close()

# Função principal
async def main():
    urls = [
        "https://ai.pydantic.dev/agents/",
        "https://ai.pydantic.dev/models/",
        "https://ai.pydantic.dev/dependencies/",
        "https://ai.pydantic.dev/tools/"
    ]
    await crawl_sequential(urls)

# Executar a função principal (usando await no Colab)
await main()

"""# V3 - 🔥 Faz o Crawler e baixa diretamente no Desktop 🔥
OBS.: Eu estava colocando pra salvar no Drive mas a a versão do crawl4ai (0.4.247) que você está usando não suporta o argumento output_dir no construtor CrawlerRunConfig.

**Explicações:**

1. **`temp_output_directory = "/content/crawl4ai_temp_output"`:** Define um diretório temporário dentro do ambiente do Colab para armazenar os arquivos Markdown.
2. **`crawl_sequential` (modificada):**
    *   O `output_dir` foi removido do `CrawlerRunConfig`.
    *   Os arquivos são salvos temporariamente no `temp_output_directory` usando a lógica que discutimos anteriormente (`os.makedirs`, `with open...`).
3. **`shutil.make_archive("crawl4ai_output", 'zip', temp_output_directory)`:**
    *   Após o rastreamento, esta linha usa a função `make_archive` do módulo `shutil` para compactar o diretório temporário em um arquivo chamado `crawl4ai_output.zip`.
4. **`files.download("crawl4ai_output.zip")`:** Esta linha usa a função `download` do `google.colab.files` para disponibilizar o arquivo zipado para download no seu navegador.

**Como executar:**

1. Execute o código.
2. O código irá rastrear as URLs e salvar os arquivos Markdown temporariamente.
3. Ao final da execução, o arquivo `crawl4ai_output.zip` será baixado automaticamente pelo seu navegador.
4. Descompacte o arquivo `.zip` para acessar os arquivos Markdown.

**Limpeza (opcional):**

*   Você pode adicionar o seguinte código ao final da função `main()` para remover o diretório temporário após o download, se desejar:

```python
shutil.rmtree(temp_output_directory)
print(f"Temporary output directory removed: {temp_output_directory}")
```

Esta solução alternativa permite que você baixe os arquivos gerados pelo `crawl4ai` como um arquivo zipado, mesmo que esteja enfrentando problemas com o argumento `output_dir`.

"""

# Instalar dependências
!pip install -U crawl4ai
!crawl4ai-setup
!crawl4ai-doctor
!python -m playwright install --with-deps chromium

# Importar bibliotecas
import asyncio
from typing import List
from crawl4ai import AsyncWebCrawler, BrowserConfig, CrawlerRunConfig
from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator
import os
import shutil
from google.colab import files

# Definir o diretório temporário para salvar os arquivos
temp_output_directory = "/content/crawl4ai_temp_output"

# Função para rastreamento sequencial
async def crawl_sequential(urls: List[str]):
    print("\n=== Sequential Crawling with Session Reuse ===")

    browser_config = BrowserConfig(
        headless=True,
        extra_args=["--disable-gpu", "--disable-dev-shm-usage", "--no-sandbox"],
    )

    crawl_config = CrawlerRunConfig(
        markdown_generator=DefaultMarkdownGenerator()
        # Sem output_dir
    )

    # Criar o crawler (abre o navegador)
    crawler = AsyncWebCrawler(config=browser_config)
    await crawler.start()

    try:
        session_id = "session1"  # Reutilizar a mesma sessão em todas as URLs
        for url in urls:
            result = await crawler.arun(
                url=url,
                config=crawl_config,
                session_id=session_id
            )
            if result.success:
                print(f"Successfully crawled: {url}")
                print(f"Markdown length: {len(result.markdown_v2.raw_markdown)}")

                # Salvar o arquivo temporariamente
                filename = os.path.join(temp_output_directory, f"{url.replace('/', '_')}.md")
                os.makedirs(os.path.dirname(filename), exist_ok=True)
                with open(filename, "w") as f:
                    f.write(result.markdown_v2.raw_markdown)
                print(f"Markdown saved to: {filename}")

            else:
                print(f"Failed: {url} - Error: {result.error_message}")
    finally:
        # Depois que todas as URLs forem concluídas, fechar o crawler (e o navegador)
        await crawler.close()

# Função principal - ⚠️INSIRA AQUI AS URLs para Crawler⚠️
async def main():
    urls = [
        "https://ai.pydantic.dev/agents/",
        "https://ai.pydantic.dev/models/",
        "https://ai.pydantic.dev/dependencies/",
        "https://ai.pydantic.dev/tools/"
    ]
    await crawl_sequential(urls)

    # Compactar a pasta de saída
    shutil.make_archive("crawl4ai_output", 'zip', temp_output_directory)
    print(f"Output directory zipped to crawl4ai_output.zip")

    # Disponibilizar para download
    files.download("crawl4ai_output.zip")

# Executar a função principal
await main()

"""# V3.1 - 🔥 Faz o Crawler e baixa diretamente no Desktop 🔥 (COM SEPARAÇÃO DE CÉLULAS)
OBS.: Eu estava colocando pra salvar no Drive mas a a versão do crawl4ai (0.4.247) que você está usando não suporta o argumento output_dir no construtor CrawlerRunConfig.

**Explicações:**

1. **`temp_output_directory = "/content/crawl4ai_temp_output"`:** Define um diretório temporário dentro do ambiente do Colab para armazenar os arquivos Markdown.
2. **`crawl_sequential` (modificada):**
    *   O `output_dir` foi removido do `CrawlerRunConfig`.
    *   Os arquivos são salvos temporariamente no `temp_output_directory` usando a lógica que discutimos anteriormente (`os.makedirs`, `with open...`).
3. **`shutil.make_archive("crawl4ai_output", 'zip', temp_output_directory)`:**
    *   Após o rastreamento, esta linha usa a função `make_archive` do módulo `shutil` para compactar o diretório temporário em um arquivo chamado `crawl4ai_output.zip`.
4. **`files.download("crawl4ai_output.zip")`:** Esta linha usa a função `download` do `google.colab.files` para disponibilizar o arquivo zipado para download no seu navegador.

**Como executar:**

1. Execute o código.
2. O código irá rastrear as URLs e salvar os arquivos Markdown temporariamente.
3. Ao final da execução, o arquivo `crawl4ai_output.zip` será baixado automaticamente pelo seu navegador.
4. Descompacte o arquivo `.zip` para acessar os arquivos Markdown.

📌**Fluxo de trabalho recomendado:** (📌NOVIDADE v3.1📌)

1. **Execute a célula de dependências uma vez** no início ou sempre que precisar instalar ou atualizar uma biblioteca.
2. **Reinicie o ambiente de execução (Runtime -> Restart runtime)** após instalar as dependências (especialmente se você atualizou uma biblioteca). Isso garante que as novas versões das bibliotecas sejam carregadas corretamente.
3. **Execute as células de código principal** sempre que fizer alterações no código e precisar testá-las. Você não precisa executar a célula de dependências novamente, a menos que precise alterar as bibliotecas instaladas.

**Limpeza (opcional):**

*   Você pode adicionar o seguinte código ao final da função `main()` para remover o diretório temporário após o download, se desejar:

```python
shutil.rmtree(temp_output_directory)
print(f"Temporary output directory removed: {temp_output_directory}")
```

Esta solução alternativa permite que você baixe os arquivos gerados pelo `crawl4ai` como um arquivo zipado, mesmo que esteja enfrentando problemas com o argumento `output_dir`.

## 1. Célula de dependências:
"""

# Instalar dependências (execute esta célula apenas uma vez ou quando precisar atualizar as bibliotecas)
!pip install -U crawl4ai
!crawl4ai-setup
!crawl4ai-doctor
!python -m playwright install --with-deps chromium

"""## 2. Células de código principal:"""

# Importar bibliotecas (execute esta célula sempre que reiniciar o ambiente de execução)
import asyncio
from typing import List
from crawl4ai import AsyncWebCrawler, BrowserConfig, CrawlerRunConfig
from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator
import os
import shutil
from google.colab import files

# Definir o diretório temporário para salvar os arquivos
temp_output_directory = "/content/crawl4ai_temp_output"

# ... (o restante do seu código)

"""## 3. Fluxo de trabalho recomendado:"""

# Função para rastreamento sequencial
async def crawl_sequential(urls: List[str]):
    print("\n=== Sequential Crawling with Session Reuse ===")

    browser_config = BrowserConfig(
        headless=True,
        extra_args=["--disable-gpu", "--disable-dev-shm-usage", "--no-sandbox"],
    )

    crawl_config = CrawlerRunConfig(
        markdown_generator=DefaultMarkdownGenerator()
        # Sem output_dir
    )

    # Criar o crawler (abre o navegador)
    crawler = AsyncWebCrawler(config=browser_config)
    await crawler.start()

    try:
        session_id = "session1"  # Reutilizar a mesma sessão em todas as URLs
        for url in urls:
            result = await crawler.arun(
                url=url,
                config=crawl_config,
                session_id=session_id
            )
            if result.success:
                print(f"Successfully crawled: {url}")
                print(f"Markdown length: {len(result.markdown_v2.raw_markdown)}")

                # Salvar o arquivo temporariamente
                filename = os.path.join(temp_output_directory, f"{url.replace('/', '_')}.md")
                os.makedirs(os.path.dirname(filename), exist_ok=True)
                with open(filename, "w") as f:
                    f.write(result.markdown_v2.raw_markdown)
                print(f"Markdown saved to: {filename}")

            else:
                print(f"Failed: {url} - Error: {result.error_message}")
    finally:
        # Depois que todas as URLs forem concluídas, fechar o crawler (e o navegador)
        await crawler.close()

# Função principal - ⚠️INSIRA AQUI AS URLs para Crawler⚠️
async def main():
    urls = [
        "https://ai.pydantic.dev/agents/",
        "https://ai.pydantic.dev/models/",
        "https://ai.pydantic.dev/dependencies/",
        "https://ai.pydantic.dev/tools/"
    ]
    await crawl_sequential(urls)

    # Compactar a pasta de saída
    shutil.make_archive("crawl4ai_output", 'zip', temp_output_directory)
    print(f"Output directory zipped to crawl4ai_output.zip")

    # Disponibilizar para download
    files.download("crawl4ai_output.zip")

# Executar a função principal
await main()